# Generated by Django 4.2.7 on 2024-02-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=10)),
                ('flightName', models.CharField(max_length=50)),
                ('journeyDate', models.DateField()),
                ('depatureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('flightFrom', models.CharField(max_length=50)),
                ('flightTo', models.CharField(max_length=50)),
                ('seatcount', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journeyDate', models.DateField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking_app.fightdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
