# Generated by Django 4.2.7 on 2024-02-24 04:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0002_rename_fightdata_flightdata'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookingdata',
            managers=[
                ('bookingobject', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='flightdata',
            managers=[
                ('flightobject', django.db.models.manager.Manager()),
            ],
        ),
    ]
