# Generated by Django 4.2.7 on 2024-02-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0003_alter_bookingdata_managers_alter_flightdata_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='num_seats',
            field=models.IntegerField(default=1),
        ),
    ]
