# Generated by Django 4.2.7 on 2024-02-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_app', '0004_bookingdata_num_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdata',
            name='journeyDate',
        ),
    ]
